import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Phone, Mail, Calendar, MapPin, CheckCircle, Clock, Send, Database, ExternalLink, Loader2, Save } from "lucide-react";
import { getLead, Lead, sendEmail, updateLead } from "@/lib/api";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useState, useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export default function LeadDetails() {
  const { leadId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [lead, setLead] = useState<Lead | null>(null);
  const [loading, setLoading] = useState(true);
  const [pushing, setPushing] = useState(false);
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState(user?.email || "");
  const [sendingEmail, setSendingEmail] = useState(false);
  const [notes, setNotes] = useState("");
  const [isVerified, setIsVerified] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (leadId) {
      loadLead(leadId);
    }
  }, [leadId]);

  useEffect(() => {
    if (user?.email && !recipientEmail) {
      setRecipientEmail(user.email);
    }
  }, [user?.email]);

  async function loadLead(id: string) {
    try {
      const data = await getLead(id);
      setLead(data);
      if (data) {
        setNotes(data.notes || "");
        setIsVerified(!!data.verified);
      }
    } catch (err) {
      console.error("Error loading lead:", err);
    } finally {
      setLoading(false);
    }
  }

  const handleSaveWorkspace = async () => {
    if (!lead) return;
    setSaving(true);
    try {
      await updateLead(lead.id, { notes, verified: isVerified });
      toast.success("Lead workspace updated");
    } catch (err) {
      toast.error("Failed to update workspace");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-20">
        <Loader2 className="h-10 w-10 animate-spin text-blue-600 mb-4" />
        <p className="text-slate-500 font-medium">Extracting Prospect Data...</p>
      </div>
    );
  }

  if (!lead) {
    return (
      <div className="p-8 text-center bg-white border rounded-xl">
        <p className="text-xl text-slate-500">Lead not found</p>
        <Button variant="link" onClick={() => navigate("/app/leads")}>Back to Leads</Button>
      </div>
    );
  }

  const handleEmailInfo = () => {
    setIsEmailDialogOpen(true);
  };

  const confirmSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    setSendingEmail(true);
    
    try {
      await sendEmail({
        to: recipientEmail,
        subject: `Prospect Insight Report: ${lead.name}`,
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #334155;">
            <h1 style="color: #2563eb;">Prospect Insight Report</h1>
            <p>Here is the detailed information for the lead captured via VertexAgent.</p>
            <div style="background-color: #f8fafc; padding: 20px; border-radius: 12px; border: 1px solid #e2e8f0;">
              <h2 style="margin-top: 0;">Contact Details</h2>
              <p><strong>Name:</strong> ${lead.name}</p>
              <p><strong>Email:</strong> ${lead.email || "Not provided"}</p>
              <p><strong>Phone:</strong> ${lead.phone || "Not provided"}</p>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
              <h2>Interaction History</h2>
              <p><strong>Property:</strong> ${lead.listingAddress}</p>
              <p><strong>Status:</strong> ${lead.status || 'New'}</p>
              <p><strong>Captured On:</strong> ${format(lead.createdAt, "PPP")}</p>
            </div>
            
            <div style="margin-top: 24px; text-align: center; border-radius: 8px;">
              <a href="${window.location.origin}/app/leads/${lead.id}" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: #ffffff; text-decoration: none; font-weight: bold; border-radius: 8px; font-size: 14px; box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.2);">→ View Lead in Agent Portal</a>
            </div>

            <p style="font-size: 11px; color: #94a3b8; margin-top: 20px; text-align: center;">
              Generated by VertexAgent AI Core. Proprietary and Confidential.
            </p>
          </div>
        `,
        text: `Prospect Insight Report for ${lead.name}\n\nProperty: ${lead.listingAddress}\nStatus: ${lead.status || 'New'}\n\nAccess the Agent Portal to view this lead: ${window.location.origin}/app/leads/${lead.id}`
      });

      setSendingEmail(false);
      setIsEmailDialogOpen(false);
      toast.success(`Contact info for ${lead.name} sent to ${recipientEmail}`, {
        description: "The report has been delivered to your inbox."
      });
    } catch (error: any) {
      setSendingEmail(false);
      toast.error("Failed to send email", {
        description: error.message || "Please check your Secrets/SMTP configuration."
      });
    }
  };

  const handlePushCRM = () => {
    toast.error("CRM Integration Not Set Up", {
      description: "Please configure a CRM webhook in Listing Settings or Integrations page first.",
      action: {
        label: "Fix Now",
        onClick: () => navigate("/app/integrations")
      }
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white border border-slate-200 p-4 rounded-xl shadow-sm">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate(-1)} className="p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-500 hover:text-slate-900">
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900">{lead.name}</h1>
            <p className="text-slate-500 text-sm">Lead information & Prospecting data</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2 items-center">
          <Button variant="outline" size="sm" onClick={handleEmailInfo} className="gap-2 font-bold shadow-sm">
            <Send className="h-4 w-4" /> Email me Info
          </Button>
          <Button variant="secondary" size="sm" onClick={handlePushCRM} disabled={pushing} className="gap-2 font-bold shadow-sm relative group">
            <Database className="h-4 w-4" /> Push to CRM
          </Button>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-white border rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-semibold mb-4 border-b pb-2 text-left">Contact Details</h2>
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <Phone className="h-5 w-5 text-slate-400" />
              <div className="text-left">
                <div className="text-sm text-slate-500">Phone</div>
                {lead.phone ? (
                  <a href={`tel:${lead.phone.replace(/[^0-9+]/g, '')}`} className="font-medium text-blue-600 hover:underline">{lead.phone}</a>
                ) : (
                  <span className="text-slate-400 italic">Not provided</span>
                )}
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Mail className="h-5 w-5 text-slate-400" />
              <div className="text-left">
                <div className="text-sm text-slate-500">Email</div>
                {lead.email ? (
                  <a href={`mailto:${lead.email}`} className="font-medium text-blue-600 hover:underline">{lead.email}</a>
                ) : (
                  <span className="text-slate-400 italic">Not provided</span>
                )}
              </div>
            </div>
            <div className="flex items-center gap-3">
              <CheckCircle className={`h-5 w-5 ${isVerified ? 'text-green-500' : 'text-slate-400'}`} />
              <div className="text-left">
                <div className="text-sm text-slate-500 flex items-center justify-between gap-4">
                    Status
                    {isVerified && <span className="text-[10px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded uppercase font-bold">Verified</span>}
                </div>
                <span className={`px-2.5 py-0.5 mt-1 inline-block rounded-full text-xs font-semibold
                    ${lead.status === 'Hot' ? 'bg-red-100 text-red-700' : ''}
                    ${lead.status === 'Warm' ? 'bg-orange-100 text-orange-700' : ''}
                    ${lead.status === 'Cold' ? 'bg-blue-100 text-blue-700' : ''}
                    ${lead.status === 'New' || !lead.status ? 'bg-green-100 text-green-700' : ''}
                  `}>
                  {lead.status || 'New'}
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white border rounded-xl p-6 shadow-sm">
          <h2 className="text-lg font-semibold mb-4 border-b pb-2 text-left">Interaction History</h2>
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <MapPin className="h-5 w-5 text-slate-400" />
              <div className="text-left">
                <div className="text-sm text-slate-500">Interested Property</div>
                <div className="font-medium">{lead.listingAddress}</div>
                <div className="text-[10px] text-slate-400">ID: {lead.listingId}</div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Calendar className="h-5 w-5 text-slate-400" />
              <div className="text-left">
                <div className="text-sm text-slate-500">Captured On</div>
                <div className="font-medium">{format(lead.createdAt, "PPP 'at' p")}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white border rounded-xl p-6 shadow-sm">
        <h2 className="text-lg font-semibold mb-4 border-b pb-2 text-left">Visitor Message</h2>
        <div className="p-4 bg-slate-50 rounded-lg text-slate-700 text-left whitespace-pre-wrap">
          {lead.message || "No message provided."}
        </div>
      </div>

      <div className="bg-white border rounded-xl p-6 shadow-sm">
        <div className="flex justify-between items-center mb-4 border-b pb-2">
          <h2 className="text-lg font-semibold">Lead Workspace</h2>
          <Button onClick={handleSaveWorkspace} disabled={saving} size="sm" className="gap-2 font-bold">
            {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
            Save Changes
          </Button>
        </div>
        <div className="space-y-4">
          <div className="flex items-center gap-3 p-3 bg-blue-50/50 rounded-lg border border-blue-100 max-w-sm">
            <div className="relative flex items-center">
              <input 
                type="checkbox" 
                id="verified" 
                checked={isVerified} 
                onChange={() => setIsVerified(!isVerified)} 
                className="h-5 w-5 rounded border-slate-300 text-blue-600 focus:ring-blue-500 cursor-pointer accent-blue-600"
              />
            </div>
            <Label htmlFor="verified" className="font-semibold text-slate-800 cursor-pointer select-none">
              Prospect Verified ✓
            </Label>
          </div>
          <div className="space-y-2 text-left">
            <Label htmlFor="notes" className="font-semibold text-slate-700">Notes (First letter capitalized)</Label>
            <Textarea 
              id="notes" 
              value={notes} 
              onChange={(e) => {
                const val = e.target.value;
                const capitalized = val.replace(/^\s*([a-z])/, (match) => match.toUpperCase());
                setNotes(capitalized);
              }} 
              placeholder="Add agent notes here..." 
              className="min-h-[120px] bg-slate-50 focus:bg-white transition-all text-slate-800"
            />
          </div>
        </div>
      </div>

      <Dialog open={isEmailDialogOpen} onOpenChange={setIsEmailDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Email Prospect Report</DialogTitle>
            <DialogDescription>
              Confirm or edit the email address where the detailed report for {lead.name} should be sent.
            </DialogDescription>
          </DialogHeader>
          <form onSubmit={confirmSendEmail} className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="email" className="font-bold text-slate-700">Recipient Email</Label>
              <Input 
                id="email" 
                type="email" 
                value={recipientEmail} 
                onChange={(e) => setRecipientEmail(e.target.value)} 
                required 
                placeholder="your@email.com"
                className="h-11"
              />
              <p className="text-[10px] text-slate-400">This will be used for this specific export only.</p>
            </div>
            <DialogFooter className="sm:justify-end gap-2 border-t pt-4">
              <Button type="button" variant="ghost" onClick={() => setIsEmailDialogOpen(false)}>Cancel</Button>
              <Button type="submit" disabled={sendingEmail} className="bg-blue-600 hover:bg-blue-500 font-bold px-8">
                {sendingEmail ? "Sending..." : "Submit"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
